project:
  type: website
  output-dir: "."

website:
  title: "Jordan Alfano"
  navbar: 
    pinned: true
    left:
      - text: Project
        href: danl_210_project.ipynb
      - text: Blog
        href: blog-listing.qmd
        menu: 
          - text: Spotify with ipynb
          - href: posts/spotify.ipynb
          - text: Python Data Aanalysis
        
          
          - text: Python Basic with ipynb
            href: basic-python-intro.ipynb
          - text: Python Basic with Pandas
            href: basic_python_intro2.ipynb
      - text: DANL 210 - Lectures
        menu: 
          - text: Lecture 06
            href: https://bcdanl.github.io/210/danl-lec/danl-210-lec-06-2024-0208.html
          - text: Lecture 07
            href: https://bcdanl.github.io/210/danl-lec/danl-210-lec-07-2024-0213.html
            
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Jordan, 2024"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
