project: 
  type: website
  output-dir: "." 

website:
  title: "Jordan A"
  navbar:
    pinned: true
    left:
      - text: Project 320
        href: danl_proj_nba.ipynb
      - text: R Basics
        href: danl-310-quarto-r.qmd
      - text: Python DANL
        menu: 
          - text: Python
            href: danl-320-python-basic.ipynb
          - text: Pandas
            href: pandas_basics.ipynb
          - text: Seaborn
            href: seaborn_basics.ipynb
    
      - text: Project NBA
        menu:  
          - text: danl_proj_nba.ipynb
          
      - text: PySpark
        menu:
          - text: Explanation of all three 
            href: PySpark.ipynb

      - text: Blog
        href: blog-listing.qmd
    
            
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Jordan, 2024"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
