---
title: DANL Project
subtitle: "Data-Driven Mastery: Unlocking Business Potential"
author: 
  - Jocelyn Matusiak
  - Jordan Alfano
  - Julia Candee
  - Sophia Frisiras

toc: true
toc-title: "Table of Contents"
toc-depth: 2
number-sections: true

fig-width: 9

execute:
  code-tools: true
  message: false
  warning: false

---


```{r setup, include = FALSE}
library(tidyverse)
library(hrbrthemes)
library(skimr)

```


```{r}
day_wise <- read_csv('https://jem10126.github.io/day_wise.csv')
nvars <- format(round(ncol(day_wise), 0), 
                nsmall=0, 
                big.mark=",") 
nobs <- format(round(nrow(day_wise), 0), 
                nsmall=0, 
                big.mark=",")
```

```{r}
rmarkdown::paged_table(day_wise) 
```

```{r}
day_wise %>% 
  ggplot(aes(x = log(Deaths), 
             y = log(Recovered))) + 
  geom_point(alpha = .1, color = 'purple') +
  geom_smooth(method = lm, se = F) +
  theme_bw() +
  theme(legend.position = 'top')
```


```{r}
day_wise <- day_wise %>% 
  group_by(Deaths, Recovered) %>% 
  summarise(Recovered_tot = sum(Recovered, na.rm = T),
            Deaths_mean = round(mean(Deaths, na.rm = T), 2),
            .groups = "drop") 

```
rmarkdown::paged_table(day_wise) 


# Example Title {.unnumbered}
- This is an unnumbered section.




## Analysis


## Quotes
- Quote with `>`

> "The truth is rarely pure and never simple."
>
> --- Oscar Wilde



## Inserting Figures
For a demonstration of a DANL tiger, see @fig-tiger.



<br><br><br><br>

# References

- [https://quarto.org/docs/output-formats/html-basics.html](https://quarto.org/docs/output-formats/html-basics.html)

- [https://quarto.org/docs/websites/](https://quarto.org/docs/websites/)

- [R for Data Science](http://r4ds.hadley.nz) by [Hadley Wickham](https://hadley.nz)
