---
title: "Classwork_10"
editor: visual
---

billboard \<- read_csv('https://bcdanl.github.io/data/billboard.csv')

Q1a.) Describe how the distribution of rating varies across week 1, week 2, and week 3 using the faceted histogram.

Q1b.) Which artist(s) have the most number of tracks in billboard data.frame?

Do not double-count an artist's tracks if they appear in multiple weeks.

Question 2 - Average Personal Income in NY Counties The following data is for Question 2:

ny_pincp \<- read_csv('https://bcdanl.github.io/data/NY_pinc_wide.csv')

Q2a Make ny_pincp longer.

Q2b Provide both (1) ggplot code and (2) a simple comment to describe how overall the yearly trend of NY counties' average personal incomes are.

Question 3 - COVID-19 Cases The following data is for Question 3:

covid \<- read_csv('https://bcdanl.github.io/data/covid19_cases.csv')

Q3a Keep only the following three variables, date, countriesAndTerritories, and cases.

Then make a wide-form data.frame of covid whose variable names are from countriesAndTerritories and values are from cases.

Then drop the variable date.

Q3b Use the wide-form data.frame of covid to find the top 10 countries in terms of the correlation between their cases and the USA case. Use cor(data.frame), which returns a matrix. Then convert it to data.frame using as.data.frame(matrix) ---
